#!/bin/bash
# colors

# Reset
Off='\033[0m'       # Text Reset

# Regular Colors
export Black='\033[0;30m'        # Black
export Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# function colorTest() {
#   echo
#   echo "reg  bld  und  bckg hi-int bld-hi-int bg-hi-int"
#   echo "${Black}Text ${BBlack}Text ${UBlack}Text${Off} ${On_Black}Text${Off} ${IBlack}Text   ${BIBlack}Text       ${On_IBlack}Text${Off}"
#   echo "${Red}Text ${BRed}Text ${URed}Text${Off} ${On_Red}Text${Off} ${IRed}Text   ${BIRed}Text       ${On_IRed}Text${Off}"
#   echo "${Green}Text ${BGreen}Text ${UGreen}Text${Off} ${On_Green}Text${Off} ${IGreen}Text   ${BIGreen}Text       ${On_IGreen}Text${Off}"
#   echo "${Yellow}Text ${BYellow}Text ${UYellow}Text${Off} ${On_Yellow}Text${Off} ${IYellow}Text   ${BIYellow}Text       ${On_IYellow}Text${Off}"
#   echo "${Blue}Text ${BBlue}Text ${UBlue}Text${Off} ${On_Blue}Text${Off} ${IBlue}Text   ${BIBlue}Text       ${On_IGreen}Text${Off}"
#   echo "${Purple}Text ${BPurple}Text ${UPurple}Text${Off} ${On_Purple}Text${Off} ${IPurple}Text   ${BIPurple}Text       ${On_IPurple}Text${Off}"
#   echo "${Cyan}Text ${BCyan}Text ${UCyan}Text${Off} ${On_Cyan}Text${Off} ${ICyan}Text   ${BICyan}Text       ${On_ICyan}Text${Off}"
#   echo "${White}Text ${BWhite}Text ${UWhite}Text${Off} ${On_White}Text${Off} ${IWhite}Text   ${BIWhite}Text       ${On_IWhite}Text${Off}"
#   echo
# }

# function colors() {
#   cd "$DOT_PATH"/bash; mvim
# }

# function tputcolors() {
#   echo
#   echo -e "$(tput bold) reg  bld  und   tput-command-colors$(tput sgr0)"
#
#   for i in $(seq 1 7); do
#     echo " $(tput setaf $i)Text$(tput sgr0) $(tput bold)$(tput setaf $i)Text$(tput sgr0) $(tput sgr 0 1)$(tput setaf $i)Text$(tput sgr0)  \$(tput setaf $i)"
#   done
#
#   echo ' Bold            $(tput bold)'
#   echo ' Underline       $(tput sgr 0 1)'
#   echo ' Reset           $(tput sgr0)'
#   echo
# }
